version: "3"

services:

  dev:
    container_name: local-serverless-dev
    build:
      context: .
    # docker run -i
    stdin_open: true
    # docker run -t
    tty: true
    networks:
      - localstack
    volumes:
      - "./data:/usr/src/app/data"
      - "./aws:/root/.aws"

  localstack:
    container_name: local-serverless-localstack
    image: localstack/localstack:1.0.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    hostname: localstack
    networks:
      - localstack
    # https://docs.localstack.cloud/localstack/configuration
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      # FIXME use "local" otherwise it can't access the lambda from the other container
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_SOCK=unix:///var/run/docker.sock
    volumes:
      - ".localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  localstack:
