version: "3"

services:

  localstack:
    container_name: local-localstack
    image: localstack/localstack:1.0.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    # https://docs.localstack.cloud/localstack/configuration
    # TODO https://docs.localstack.cloud/tools/lambda-tools/hot-swapping
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_SOCK=unix:///var/run/docker.sock
    volumes:
      - ".localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
