version: "3"

services:

  dev:
    container_name: local-serverless-sqs-dev
    build:
      context: .
    # docker run -i
    stdin_open: true
    # docker run -t
    tty: true
    networks:
      - localstack
    volumes:
      - "./data:/usr/src/app/data"
      - "./aws:/root/.aws"

  localstack:
    container_name: local-serverless-sqs-localstack
    image: localstack/localstack:1.1.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    hostname: localstack
    networks:
      - localstack
    # https://docs.localstack.cloud/localstack/configuration
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      # custom
      - BUCKET_NAME=my-bucket
      - QUEUE_NAME=MyQueue
    volumes:
      - ".localstack:/var/lib/localstack"
      # run custom scripts: requires credentials
      - "./aws:/root/.aws"
      - './entrypoint:/docker-entrypoint-initaws.d'

networks:
  localstack:
