version: "3.8"
name: "http-server"
services:

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_DB=example_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword

  # http://localhost:9090/?pgsql=postgres&username=postgres&db=example_db
  postgres-ui:
    image: adminer:4
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    depends_on:
      - postgres
