apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "application.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.httpPort }}
      targetPort: http-svc
