namespace: INVALID_NAMESPACE
nameOverride: ""
fullnameOverride: ""

image:
  repository: niqdev/kotlin-fun-http
  tag: latest
  # default is IfNotPresent
  pullPolicy: Always

env:
  - name: SERVER_NAME
    value: "kotlin-fun-http-example"
  - name: POSTGRES_URL
    # format [service-name].[namespace].svc.cluster.local
    # TODO extract config hostname and override it in the app using the interpolated namespace
    value: "jdbc:postgresql://kotlin-fun-database.examples.svc.cluster.local:5432/example_db"

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 256Mi

app:
  version: main-v0.1.0
  replicas: 1
  httpPort: 8080

# see alias in Chart.yaml: it changes service-name from "kotlin-fun-postgres" to "kotlin-fun-database"
database:
  image:
    repository: postgres
    # TODO chart compatible only with v11 use bitnami for latest version (oci registry issue in argo)
    tag: "11-alpine"
  # TODO use secret operator
  postgresql:
    username: postgres
    password: pgpassword
    database: example_db
