name: Update Gradle Wrapper

on:
  schedule:
    # once a day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # required for buildSrc only, fixes "Could not resolve project :buildSrc"
      # last failing workflow https://github.com/niqdev/kotlin-fun/actions/runs/7717490036
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
